[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$Manifest)
$ErrorActionPreference='Stop'
try { $path=(Resolve-Path -LiteralPath $Manifest).Path; $doc=Get-Content -Raw -LiteralPath $path | ConvertFrom-Json } catch { Write-Error "Unable to load JSON-compatible YAML UX manifest '$Manifest': $($_.Exception.Message)"; exit 2 }
$errors=[Collections.Generic.List[string]]::new()
function Add-Error([string]$Message){$errors.Add($Message)}
foreach($name in @('shell','pages','components','journeys','visual_acceptance')){if(-not ($doc.PSObject.Properties.Name -contains $name)){Add-Error "$name is required"}}
if($errors.Count){$errors|ForEach-Object{"ERROR: $_"}; exit 1}
$pages=@($doc.pages); $components=@($doc.components); $journeys=@($doc.journeys)
if(-not $pages.Count){Add-Error 'pages must be a non-empty list'}; if(-not $components.Count){Add-Error 'components must be a non-empty list'}; if(-not $journeys.Count){Add-Error 'journeys must be a non-empty list'}
function Index-ById($items,[string]$label){$map=@{};$n=0;foreach($item in $items){if(-not ($item.PSObject.Properties.Name -contains 'id') -or [string]::IsNullOrWhiteSpace([string]$item.id)){Add-Error "$label[$n].id is required"}elseif($map.ContainsKey([string]$item.id)){Add-Error "duplicate $label id: $($item.id)"}else{$map[[string]$item.id]=$item};$n++};return $map}
$pageById=Index-ById $pages 'pages'; $componentById=Index-ById $components 'components'; $journeyById=Index-ById $journeys 'journeys'
$roles=@{}; foreach($role in @($doc.roles)){if($role.code){$roles[[string]$role.code]=$true}}
$navIds=@{}; foreach($nav in @($doc.shell.navigation)){$navIds[[string]$nav.id]=$true;if(-not $pageById.ContainsKey([string]$nav.target)){Add-Error "navigation target does not exist: $($nav.target)"}}
if(-not $navIds.ContainsKey([string]$doc.shell.primary_create_action)){Add-Error 'shell.primary_create_action must name a navigation item'}
foreach($pageId in $pageById.Keys){$page=$pageById[$pageId];if($page.PSObject.Properties.Name -contains 'roles'){foreach($role in @($page.roles)){if($role -and -not $roles.ContainsKey([string]$role)){Add-Error "page $pageId references unknown role: $role"}}};if($page.PSObject.Properties.Name -contains 'components'){foreach($component in @($page.components)){if($component -and -not $componentById.ContainsKey([string]$component)){Add-Error "page $pageId references unknown component: $component"}}};foreach($key in @('component','persistent_header','lifecycle','action_panel')){if($page.PSObject.Properties.Name -contains $key){$value=[string]$page.$key;if($value -and -not $componentById.ContainsKey($value)){Add-Error "page $pageId.$key references unknown component: $value"}}};if($page.PSObject.Properties.Name -contains 'journey' -and -not $journeyById.ContainsKey([string]$page.journey)){Add-Error "page $pageId references unknown journey: $($page.journey)"}}
foreach($id in $componentById.Keys){$c=$componentById[$id];$kind=[string]$c.kind;if($kind -in @('kpi','chart')){foreach($field in @('measure','drilldown')){if(-not ($c.PSObject.Properties.Name -contains $field) -or [string]::IsNullOrWhiteSpace([string]$c.$field)){Add-Error "$kind $id requires $field"}}};if($kind -eq 'chart' -and $c.table_alternative -ne $true){Add-Error "chart $id requires table_alternative: true"};if($kind -in @('chart','queue','timeline') -and (-not ($c.PSObject.Properties.Name -contains 'empty_state') -or [string]::IsNullOrWhiteSpace([string]$c.empty_state))){Add-Error "$kind $id requires empty_state"};if($c.PSObject.Properties.Name -contains 'drilldown'){$d=[string]$c.drilldown;if($d -and -not $componentById.ContainsKey($d) -and -not $pageById.ContainsKey($d)){Add-Error "component $id drilldown target does not exist: $d"}}}
foreach($id in $journeyById.Keys){$j=$journeyById[$id];$steps=@($j.steps);if($steps.Count -lt 2){Add-Error "journey $id requires at least two steps"};if($j.review_before_submit -ne $true){Add-Error "journey $id requires review_before_submit: true"};if(-not @($steps|Where-Object{$_.summary -eq $true}).Count){Add-Error "journey $id requires a summary step"};if(-not $pageById.ContainsKey([string]$j.success_target)){Add-Error "journey $id success target does not exist: $($j.success_target)"}}
$viewportNames=@{};foreach($v in @($doc.visual_acceptance.viewports)){$viewportNames[[string]$v.name]=$true};foreach($required in @('desktop','tablet','mobile')){if(-not $viewportNames.ContainsKey($required)){Add-Error "visual_acceptance requires $required viewport"}}
$states=@{};foreach($s in @($doc.visual_acceptance.states)){$states[[string]$s]=$true};foreach($required in @('populated','empty','validation-error','long-content','read-only')){if(-not $states.ContainsKey($required)){Add-Error "visual_acceptance requires $required state"}}
if($errors.Count){$errors|ForEach-Object{"ERROR: $_"};"Validation failed with $($errors.Count) error(s).";exit 1}
"Valid case UX design manifest: $path";exit 0
