/*
Reusable ISO 3166-1 alpha-2 country lookup for K2 solutions.
Snapshot: 2026-07-25, 249 officially assigned alpha-2 entries.
Authority: https://www.iso.org/iso-3166-country-codes.html
Prepared from the public-domain country-list dataset:
https://github.com/datasets/country-list
Source commit: eae2067dd6526749ef33675c950eab3cc0804bcb

Copy this script into a solution's ordered SQL folder; do not edit the
bundled source in place. The ref.Country table is the FK target and the
ref.CountryLookup view is the parameterless SmartObject dropdown source.
*/

IF SCHEMA_ID(N'ref') IS NULL
    EXEC(N'CREATE SCHEMA ref AUTHORIZATION dbo');
GO

IF OBJECT_ID(N'ref.Country', N'U') IS NULL
BEGIN
    CREATE TABLE ref.Country
    (
        CountryCode nvarchar(2) NOT NULL,
        CountryName nvarchar(100) NOT NULL,
        IsActive bit NOT NULL CONSTRAINT DF_ref_Country_IsActive DEFAULT (1),
        SortOrder int NOT NULL,
        CONSTRAINT PK_ref_Country PRIMARY KEY (CountryCode),
        CONSTRAINT UQ_ref_Country_CountryName UNIQUE (CountryName),
        CONSTRAINT CK_ref_Country_CountryCode
            CHECK
            (
                LEN(CountryCode) = 2 AND
                CountryCode COLLATE Latin1_General_100_BIN2 NOT LIKE N'%[^A-Z]%'
            ),
        CONSTRAINT CK_ref_Country_SortOrder CHECK (SortOrder > 0)
    );
END;
GO

MERGE ref.Country WITH (HOLDLOCK) AS target
USING
(
    VALUES
    (N'AD', N'Andorra', 1),
    (N'AE', N'United Arab Emirates', 2),
    (N'AF', N'Afghanistan', 3),
    (N'AG', N'Antigua and Barbuda', 4),
    (N'AI', N'Anguilla', 5),
    (N'AL', N'Albania', 6),
    (N'AM', N'Armenia', 7),
    (N'AO', N'Angola', 8),
    (N'AQ', N'Antarctica', 9),
    (N'AR', N'Argentina', 10),
    (N'AS', N'American Samoa', 11),
    (N'AT', N'Austria', 12),
    (N'AU', N'Australia', 13),
    (N'AW', N'Aruba', 14),
    (N'AX', N'Åland Islands', 15),
    (N'AZ', N'Azerbaijan', 16),
    (N'BA', N'Bosnia and Herzegovina', 17),
    (N'BB', N'Barbados', 18),
    (N'BD', N'Bangladesh', 19),
    (N'BE', N'Belgium', 20),
    (N'BF', N'Burkina Faso', 21),
    (N'BG', N'Bulgaria', 22),
    (N'BH', N'Bahrain', 23),
    (N'BI', N'Burundi', 24),
    (N'BJ', N'Benin', 25),
    (N'BL', N'Saint Barthélemy', 26),
    (N'BM', N'Bermuda', 27),
    (N'BN', N'Brunei Darussalam', 28),
    (N'BO', N'Bolivia (Plurinational State of)', 29),
    (N'BQ', N'Bonaire, Sint Eustatius and Saba', 30),
    (N'BR', N'Brazil', 31),
    (N'BS', N'Bahamas', 32),
    (N'BT', N'Bhutan', 33),
    (N'BV', N'Bouvet Island', 34),
    (N'BW', N'Botswana', 35),
    (N'BY', N'Belarus', 36),
    (N'BZ', N'Belize', 37),
    (N'CA', N'Canada', 38),
    (N'CC', N'Cocos (Keeling) Islands', 39),
    (N'CD', N'Congo (the Democratic Republic of the)', 40),
    (N'CF', N'Central African Republic', 41),
    (N'CG', N'Congo', 42),
    (N'CH', N'Switzerland', 43),
    (N'CI', N'Côte d''Ivoire', 44),
    (N'CK', N'Cook Islands', 45),
    (N'CL', N'Chile', 46),
    (N'CM', N'Cameroon', 47),
    (N'CN', N'China', 48),
    (N'CO', N'Colombia', 49),
    (N'CR', N'Costa Rica', 50),
    (N'CU', N'Cuba', 51),
    (N'CV', N'Cabo Verde', 52),
    (N'CW', N'Curaçao', 53),
    (N'CX', N'Christmas Island', 54),
    (N'CY', N'Cyprus', 55),
    (N'CZ', N'Czechia', 56),
    (N'DE', N'Germany', 57),
    (N'DJ', N'Djibouti', 58),
    (N'DK', N'Denmark', 59),
    (N'DM', N'Dominica', 60),
    (N'DO', N'Dominican Republic', 61),
    (N'DZ', N'Algeria', 62),
    (N'EC', N'Ecuador', 63),
    (N'EE', N'Estonia', 64),
    (N'EG', N'Egypt', 65),
    (N'EH', N'Western Sahara*', 66),
    (N'ER', N'Eritrea', 67),
    (N'ES', N'Spain', 68),
    (N'ET', N'Ethiopia', 69),
    (N'FI', N'Finland', 70),
    (N'FJ', N'Fiji', 71),
    (N'FK', N'Falkland Islands (the) [Malvinas]', 72),
    (N'FM', N'Micronesia (Federated States of)', 73),
    (N'FO', N'Faroe Islands', 74),
    (N'FR', N'France', 75),
    (N'GA', N'Gabon', 76),
    (N'GB', N'United Kingdom of Great Britain and Northern Ireland', 77),
    (N'GD', N'Grenada', 78),
    (N'GE', N'Georgia', 79),
    (N'GF', N'French Guiana', 80),
    (N'GG', N'Guernsey', 81),
    (N'GH', N'Ghana', 82),
    (N'GI', N'Gibraltar', 83),
    (N'GL', N'Greenland', 84),
    (N'GM', N'Gambia', 85),
    (N'GN', N'Guinea', 86),
    (N'GP', N'Guadeloupe', 87),
    (N'GQ', N'Equatorial Guinea', 88),
    (N'GR', N'Greece', 89),
    (N'GS', N'South Georgia and the South Sandwich Islands', 90),
    (N'GT', N'Guatemala', 91),
    (N'GU', N'Guam', 92),
    (N'GW', N'Guinea-Bissau', 93),
    (N'GY', N'Guyana', 94),
    (N'HK', N'Hong Kong', 95),
    (N'HM', N'Heard Island and McDonald Islands', 96),
    (N'HN', N'Honduras', 97),
    (N'HR', N'Croatia', 98),
    (N'HT', N'Haiti', 99),
    (N'HU', N'Hungary', 100),
    (N'ID', N'Indonesia', 101),
    (N'IE', N'Ireland', 102),
    (N'IL', N'Israel', 103),
    (N'IM', N'Isle of Man', 104),
    (N'IN', N'India', 105),
    (N'IO', N'British Indian Ocean Territory', 106),
    (N'IQ', N'Iraq', 107),
    (N'IR', N'Iran (Islamic Republic of)', 108),
    (N'IS', N'Iceland', 109),
    (N'IT', N'Italy', 110),
    (N'JE', N'Jersey', 111),
    (N'JM', N'Jamaica', 112),
    (N'JO', N'Jordan', 113),
    (N'JP', N'Japan', 114),
    (N'KE', N'Kenya', 115),
    (N'KG', N'Kyrgyzstan', 116),
    (N'KH', N'Cambodia', 117),
    (N'KI', N'Kiribati', 118),
    (N'KM', N'Comoros', 119),
    (N'KN', N'Saint Kitts and Nevis', 120),
    (N'KP', N'Korea (the Democratic People''s Republic of)', 121),
    (N'KR', N'Korea (the Republic of)', 122),
    (N'KW', N'Kuwait', 123),
    (N'KY', N'Cayman Islands', 124),
    (N'KZ', N'Kazakhstan', 125),
    (N'LA', N'Lao People''s Democratic Republic', 126),
    (N'LB', N'Lebanon', 127),
    (N'LC', N'Saint Lucia', 128),
    (N'LI', N'Liechtenstein', 129),
    (N'LK', N'Sri Lanka', 130),
    (N'LR', N'Liberia', 131),
    (N'LS', N'Lesotho', 132),
    (N'LT', N'Lithuania', 133),
    (N'LU', N'Luxembourg', 134),
    (N'LV', N'Latvia', 135),
    (N'LY', N'Libya', 136),
    (N'MA', N'Morocco', 137),
    (N'MC', N'Monaco', 138),
    (N'MD', N'Moldova (the Republic of)', 139),
    (N'ME', N'Montenegro', 140),
    (N'MF', N'Saint Martin (French part)', 141),
    (N'MG', N'Madagascar', 142),
    (N'MH', N'Marshall Islands', 143),
    (N'MK', N'North Macedonia', 144),
    (N'ML', N'Mali', 145),
    (N'MM', N'Myanmar', 146),
    (N'MN', N'Mongolia', 147),
    (N'MO', N'Macao', 148),
    (N'MP', N'Northern Mariana Islands', 149),
    (N'MQ', N'Martinique', 150),
    (N'MR', N'Mauritania', 151),
    (N'MS', N'Montserrat', 152),
    (N'MT', N'Malta', 153),
    (N'MU', N'Mauritius', 154),
    (N'MV', N'Maldives', 155),
    (N'MW', N'Malawi', 156),
    (N'MX', N'Mexico', 157),
    (N'MY', N'Malaysia', 158),
    (N'MZ', N'Mozambique', 159),
    (N'NA', N'Namibia', 160),
    (N'NC', N'New Caledonia', 161),
    (N'NE', N'Niger', 162),
    (N'NF', N'Norfolk Island', 163),
    (N'NG', N'Nigeria', 164),
    (N'NI', N'Nicaragua', 165),
    (N'NL', N'Netherlands (Kingdom of the)', 166),
    (N'NO', N'Norway', 167),
    (N'NP', N'Nepal', 168),
    (N'NR', N'Nauru', 169),
    (N'NU', N'Niue', 170),
    (N'NZ', N'New Zealand', 171),
    (N'OM', N'Oman', 172),
    (N'PA', N'Panama', 173),
    (N'PE', N'Peru', 174),
    (N'PF', N'French Polynesia', 175),
    (N'PG', N'Papua New Guinea', 176),
    (N'PH', N'Philippines', 177),
    (N'PK', N'Pakistan', 178),
    (N'PL', N'Poland', 179),
    (N'PM', N'Saint Pierre and Miquelon', 180),
    (N'PN', N'Pitcairn', 181),
    (N'PR', N'Puerto Rico', 182),
    (N'PS', N'Palestine, State of', 183),
    (N'PT', N'Portugal', 184),
    (N'PW', N'Palau', 185),
    (N'PY', N'Paraguay', 186),
    (N'QA', N'Qatar', 187),
    (N'RE', N'Réunion', 188),
    (N'RO', N'Romania', 189),
    (N'RS', N'Serbia', 190),
    (N'RU', N'Russian Federation', 191),
    (N'RW', N'Rwanda', 192),
    (N'SA', N'Saudi Arabia', 193),
    (N'SB', N'Solomon Islands', 194),
    (N'SC', N'Seychelles', 195),
    (N'SD', N'Sudan', 196),
    (N'SE', N'Sweden', 197),
    (N'SG', N'Singapore', 198),
    (N'SH', N'Saint Helena, Ascension and Tristan da Cunha', 199),
    (N'SI', N'Slovenia', 200),
    (N'SJ', N'Svalbard and Jan Mayen', 201),
    (N'SK', N'Slovakia', 202),
    (N'SL', N'Sierra Leone', 203),
    (N'SM', N'San Marino', 204),
    (N'SN', N'Senegal', 205),
    (N'SO', N'Somalia', 206),
    (N'SR', N'Suriname', 207),
    (N'SS', N'South Sudan', 208),
    (N'ST', N'Sao Tome and Principe', 209),
    (N'SV', N'El Salvador', 210),
    (N'SX', N'Sint Maarten (Dutch part)', 211),
    (N'SY', N'Syrian Arab Republic', 212),
    (N'SZ', N'Eswatini', 213),
    (N'TC', N'Turks and Caicos Islands', 214),
    (N'TD', N'Chad', 215),
    (N'TF', N'French Southern Territories', 216),
    (N'TG', N'Togo', 217),
    (N'TH', N'Thailand', 218),
    (N'TJ', N'Tajikistan', 219),
    (N'TK', N'Tokelau', 220),
    (N'TL', N'Timor-Leste', 221),
    (N'TM', N'Turkmenistan', 222),
    (N'TN', N'Tunisia', 223),
    (N'TO', N'Tonga', 224),
    (N'TR', N'Türkiye', 225),
    (N'TT', N'Trinidad and Tobago', 226),
    (N'TV', N'Tuvalu', 227),
    (N'TW', N'Taiwan (Province of China)', 228),
    (N'TZ', N'Tanzania, the United Republic of', 229),
    (N'UA', N'Ukraine', 230),
    (N'UG', N'Uganda', 231),
    (N'UM', N'United States Minor Outlying Islands', 232),
    (N'US', N'United States of America', 233),
    (N'UY', N'Uruguay', 234),
    (N'UZ', N'Uzbekistan', 235),
    (N'VA', N'Holy See', 236),
    (N'VC', N'Saint Vincent and the Grenadines', 237),
    (N'VE', N'Venezuela (Bolivarian Republic of)', 238),
    (N'VG', N'Virgin Islands (British)', 239),
    (N'VI', N'Virgin Islands (U.S.)', 240),
    (N'VN', N'Viet Nam', 241),
    (N'VU', N'Vanuatu', 242),
    (N'WF', N'Wallis and Futuna', 243),
    (N'WS', N'Samoa', 244),
    (N'YE', N'Yemen', 245),
    (N'YT', N'Mayotte', 246),
    (N'ZA', N'South Africa', 247),
    (N'ZM', N'Zambia', 248),
    (N'ZW', N'Zimbabwe', 249)
) AS source (CountryCode, CountryName, SortOrder)
ON target.CountryCode = source.CountryCode
WHEN MATCHED AND
(
    target.CountryName <> source.CountryName OR
    target.SortOrder <> source.SortOrder OR
    target.IsActive = 0
)
THEN UPDATE SET
    CountryName = source.CountryName,
    SortOrder = source.SortOrder,
    IsActive = 1
WHEN NOT MATCHED BY TARGET THEN
    INSERT (CountryCode, CountryName, IsActive, SortOrder)
    VALUES (source.CountryCode, source.CountryName, 1, source.SortOrder)
WHEN NOT MATCHED BY SOURCE AND target.IsActive = 1 THEN
    UPDATE SET IsActive = 0;
GO

CREATE OR ALTER VIEW ref.CountryLookup
AS
    SELECT CountryCode, CountryName, SortOrder
    FROM ref.Country
    WHERE IsActive = 1;
GO
