using System;
using System.Linq;
using System.Xml.Linq;

namespace K2SmartFormsCli
{
    internal static class ViewMetricCardLayoutDefinition
    {
        public static string Apply(string xml, ViewDefinition view)
        {
            if (view.MetricCards == null || view.MetricCards.Count == 0) return xml;
            var document=XDocument.Parse(xml,LoadOptions.PreserveWhitespace);var root=document.Descendants().First(x=>x.Name.LocalName=="View"&&x.Attribute("ID")!=null);var ns=root.Name.Namespace;
            var controls=root.Elements().First(x=>x.Name.LocalName=="Controls");var events=root.Elements().First(x=>x.Name.LocalName=="Events");
            var init=events.Elements().First(x=>x.Name.LocalName=="Event"&&string.Equals(Child(x,"Name"),"Init",StringComparison.OrdinalIgnoreCase));
            var execute=init.Descendants().FirstOrDefault(x=>x.Name.LocalName=="Action"&&string.Equals((string)x.Attribute("Type"),"Execute",StringComparison.OrdinalIgnoreCase)&&string.Equals(ActionProperty(x,"Method"),view.DefaultListMethod,StringComparison.OrdinalIgnoreCase));
            if(execute==null)execute=BuildListActionTemplate(ns,root,view.DefaultListMethod);
            var sourceResults=execute.Descendants().Where(x=>x.Name.LocalName=="Result"&&x.Attribute("SourceID")!=null).ToList();
            var bodyGrid=root.Descendants().First(x=>x.Name.LocalName=="Section"&&string.Equals((string)x.Attribute("Type"),"Body",StringComparison.OrdinalIgnoreCase)).Elements().First(x=>x.Name.LocalName=="Control");
            var rows=bodyGrid.Elements().First(x=>x.Name.LocalName=="Rows");var originalRows=rows.Elements().Where(x=>x.Name.LocalName=="Row").ToList();
            var columns=bodyGrid.Elements().FirstOrDefault(x=>x.Name.LocalName=="Columns");var available=columns==null?1:columns.Elements().Count(x=>x.Name.LocalName=="Column");var cardsPerRow=Math.Max(1,Math.Min(available,2));var span=Math.Max(1,available/cardsPerRow);
            var mappedResults=new XElement(ns+"Results");
            for(var offset=0;offset<view.MetricCards.Count;offset+=cardsPerRow){var labelRow=new XElement(ns+"Row",new XAttribute("ID",NewId()),new XElement(ns+"Cells"));var valueRow=new XElement(ns+"Row",new XAttribute("ID",NewId()),new XElement(ns+"Cells"));foreach(var card in view.MetricCards.Skip(offset).Take(cardsPerRow)){var labelId=NewId();var valueId=NewId();controls.Add(Label(ns,labelId,"lbl"+card.Property,card.Label,card.Explanation));controls.Add(Value(ns,valueId,"dlb"+card.Property,card.Tone));labelRow.Element(ns+"Cells").Add(Cell(ns,labelId,span));valueRow.Element(ns+"Cells").Add(Cell(ns,valueId,span));var source=sourceResults.FirstOrDefault(x=>string.Equals((string)x.Attribute("SourceName"),card.Property,StringComparison.OrdinalIgnoreCase)||string.Equals((string)x.Attribute("SourceDisplayName"),card.Property,StringComparison.OrdinalIgnoreCase));if(source==null)throw new CliException("Generated View '"+view.Name+"' exposes no List result for metric property '"+card.Property+"'.");mappedResults.Add(new XElement(ns+"Result",source.Attributes().Where(a=>a.Name.LocalName.StartsWith("Source",StringComparison.Ordinal)),new XAttribute("TargetID",valueId),new XAttribute("TargetName","dlb"+card.Property),new XAttribute("TargetDisplayName",card.Label),new XAttribute("TargetType","Control")));}if(originalRows.Count>0)originalRows[0].AddBeforeSelf(labelRow,valueRow);else rows.Add(labelRow,valueRow);}
            foreach(var row in originalRows)row.Remove();var cardAction=new XElement(execute);cardAction.SetAttributeValue("ID",NewId());cardAction.SetAttributeValue("DefinitionID",NewId());var old=cardAction.Elements().FirstOrDefault(x=>x.Name.LocalName=="Results");if(old!=null)old.ReplaceWith(mappedResults);else cardAction.Add(mappedResults);var actions=init.Descendants().First(x=>x.Name.LocalName=="Actions");actions.Add(cardAction);return document.ToString(SaveOptions.DisableFormatting);
        }
        public static void Verify(string xml,ViewDefinition view){if(view.MetricCards==null||view.MetricCards.Count==0)return;var d=XDocument.Parse(xml);foreach(var card in view.MetricCards){var name="dlb"+card.Property;var c=d.Descendants().SingleOrDefault(x=>x.Name.LocalName=="Control"&&string.Equals((string)x.Attribute("Type"),"DataLabel",StringComparison.OrdinalIgnoreCase)&&string.Equals(Child(x,"Name"),name,StringComparison.OrdinalIgnoreCase));if(c==null)throw new CliException("K2 View '"+view.Name+"' is missing metric card '"+card.Label+"'.");var id=(string)c.Attribute("ID");if(!d.Descendants().Any(x=>x.Name.LocalName=="Result"&&string.Equals((string)x.Attribute("TargetID"),id,StringComparison.OrdinalIgnoreCase)))throw new CliException("K2 View '"+view.Name+"' metric card '"+card.Label+"' has no List result mapping.");}}
        private static XElement BuildListActionTemplate(XNamespace n,XElement root,string method){var source=root.Elements().First(x=>x.Name.LocalName=="Sources").Elements().First(x=>x.Name.LocalName=="Source"&&string.Equals((string)x.Attribute("ContextType"),"Primary",StringComparison.OrdinalIgnoreCase));var results=new XElement(n+"Results");foreach(var field in source.Descendants().Where(x=>x.Name.LocalName=="Field")){var name=Child(field,"FieldName")??Child(field,"Name");results.Add(new XElement(n+"Result",new XAttribute("SourceID",name),new XAttribute("SourceName",name),new XAttribute("SourceDisplayName",Child(field,"FieldDisplayName")??name),new XAttribute("SourceType","ObjectProperty")));}return new XElement(n+"Action",new XAttribute("ID",NewId()),new XAttribute("DefinitionID",NewId()),new XAttribute("Type","Execute"),new XAttribute("ExecutionType","Synchronous"),new XElement(n+"Properties",P(n,"Location","View"),P(n,"Method",method),P(n,"ViewID",(string)root.Attribute("ID"))),results);}
        private static XElement Label(XNamespace n,string id,string name,string text,string tip){return new XElement(n+"Control",new XAttribute("ID",id),new XAttribute("Type","Label"),new XElement(n+"Name",name),new XElement(n+"DisplayName",name),new XElement(n+"Properties",P(n,"ControlName",name),P(n,"Text",text),P(n,"ToolTip",tip??string.Empty)),new XElement(n+"Styles",new XElement(n+"Style",new XAttribute("IsDefault","True"),new XElement(n+"Font",new XElement(n+"Weight","Bold")))));}
        private static XElement Value(XNamespace n,string id,string name,string tone){var color=tone=="critical"?"#b42318":tone=="warning"?"#a86100":tone=="positive"?"#28755b":"#17263a";return new XElement(n+"Control",new XAttribute("ID",id),new XAttribute("Type","DataLabel"),new XElement(n+"Name",name),new XElement(n+"DisplayName",name),new XElement(n+"Properties",P(n,"ControlName",name),P(n,"Text","0"),P(n,"IsVisible","true")),new XElement(n+"Styles",new XElement(n+"Style",new XAttribute("IsDefault","True"),new XElement(n+"Font",new XElement(n+"Weight","Bold"),new XElement(n+"Color",color)),new XElement(n+"Padding",new XElement(n+"Bottom","16px")))));}
        private static XElement Cell(XNamespace n,string id,int span){return new XElement(n+"Cell",new XAttribute("ID",NewId()),new XAttribute("ColumnSpan",span),new XElement(n+"Control",new XAttribute("ID",id)));}
        private static XElement P(XNamespace n,string name,string value){return new XElement(n+"Property",new XElement(n+"Name",name),new XElement(n+"DisplayValue",value??string.Empty),new XElement(n+"NameValue",value??string.Empty),new XElement(n+"Value",value??string.Empty));}
        private static string ActionProperty(XElement a,string name){var p=a.Elements().Where(x=>x.Name.LocalName=="Properties").SelectMany(x=>x.Elements()).FirstOrDefault(x=>x.Name.LocalName=="Property"&&string.Equals(Child(x,"Name"),name,StringComparison.OrdinalIgnoreCase));return p==null?null:Child(p,"Value");}
        private static string Child(XElement e,string n){var c=e.Elements().FirstOrDefault(x=>x.Name.LocalName==n);return c==null?null:c.Value;}private static string NewId(){return Guid.NewGuid().ToString();}
    }
}
